version: "3"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "0000"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "rosatom_labs"
    ports:
      - '5432:5432'
